### ISSUE TITLE
Draft Spacebook Logo

### ISSUE THREAD

**Issue by roscoehuntera** [alyzadiaz/spacebook#10]
The idea of a book with a spaceship that spells out Spacebook.

**Comment by dshackley** [comment]
![Uploading SpacebookSAMP.PNG…]()

**Comment by dshackley** [comment]
<img width="417" alt="SpacebookSAMP" src="https://user-images.githubusercontent.com/36347389/112045301-12c4c880-8b21-11eb-95f6-3ea5703ae6bc.PNG">
