### ISSUE TITLE
Design Home Page

### ISSUE THREAD

**Issue by roscoehuntera** [alyzadiaz/spacebook#5]
1.1.1.2. Create Home Page
[REQ-1] The system shall allow users to click tabs
[REQ-2] The system shall allow users to view space graphics

**Comment by dshackley** [comment]
Link to pdf
[Home Page Design.pdf](https://github.com/alyzadiaz/spacebook/files/6152086/Home.Page.Design.pdf)

https://app.luminpdf.com/viewer/60511694cb43db00119f526a
